Testing and validation
kennyegun24/rails-blog-app pull request #3
Opened 2023-01-28 01:12 UTC by kennyegun24

### In this pr, I did the following...
- I wrote unit tests for the methods
- I validated user inputs based on projects requirements

2023-01-28 01:14 UTC, mirouhml commented
Hi @kennyegun24, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that didn't pass linters checks.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-01-28 01:21 UTC, mirouhml requested changes
# REQUIRED CHANGES 🔴

Hi @kennyegun24, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media4.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif?cid=ecf05e47n6s5huda7qh40syoppcaspe9vx68ddmxerd08owm&rid=giphy.gif&ct=g)

## Highlights

- Great job setting up the correct linters ✔️
- Highly organized and clean code ✔️ 👨🏻‍💻
- Professional documentation ✔️
- Correct workflow ✔️
- Meaningful commit messages ✔️

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-28 01:21 UTC, mirouhml commented on spec/model/users_spec.rb
> +end
- [x] Kindly add a unit test for the model method `three_posts`, as it is required to do so.

2023-01-28 01:21 UTC, mirouhml commented on spec/model/posts_spec.rb
> +end
- [x] Same as before, kindly add unit tests for post model methods, as it is required to do so.

2023-01-28 04:54 UTC, BenMukebo requested changes
### Hi @kennyegun24,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻
- No linter errors. ✔️ 
- Gitflow was correctly used.  ✔️   
- Descriptive Pull Request.  ✔️

 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] When I click the link to the `MIT.md` file that you added, I get this 404 `error`:

![00Mit](https://user-images.githubusercontent.com/79058364/182822618-fdfb2523-cb23-4060-9f72-75ec8c29e4cd.png)

- Please, update your LICENSE section with a link to the license file, as this will make your readme more informative and professional.


Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-28 04:54 UTC, BenMukebo commented on spec/model/comment_spec.rb
> +                     Photo: 'https://google.com/googleIcon.png')
- [OPTIONAL] Well done writing your validations tests so far. However, you're missing a small thing to do for the tests to be valid. Kindly make all Model specs (for `User`, `Post`, `Comment`, and `Like` model) has **Validation** tests as required in this milestone; See the example down below!
```ruby
describe 'validations' do
  it { should validate_presence_of(:name) }
end
```

2023-01-28 04:54 UTC, BenMukebo commented on spec/model/posts_spec.rb
> +  end
- [ ] According to the project requirement, 👇🏻 Any custom methods in the models should have a corresponding unit test. You're missing adding unit test of the:
1.  `update_post_counter and five_recent_comments` methods of your post model.
2. `update_comment_counter` method of your comment model and,
3. `update_likes_counter` method of your like model.
### please address this ✍🏻 

![im2](https://user-images.githubusercontent.com/79058364/215210008-f647c979-9f49-40cc-a73e-e5d3c29cfbb1.png)

2023-01-31 14:32 UTC, FrederickMih approved these changes
## Hi 🙋  @kennyegun24, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏 

- Add tests for custom methods 👍 
- PR is professional 👍 

## Optional suggestions

- **@kennyegun24, kindly note that broken links hurt user experience as requested by the previous reviewer and it makes your work looks unprofessional implying that you don't care about those using or checking your work. The license link is still not working**. It is highly recommended to fix it!

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-01 09:26 UTC, merged